### ISSUE TITLE
Evaluate additional AMP tools for inclusion

### ISSUE THREAD

**Issue by jfy133** [nf-core/funcscan#10]
### Description of feature

New modules for AMP detection included in funcscan 
- [x] Amplify
  https://anaconda.org/bioconda/amplify
- [x] EnsembleAMPPred
  http://ncrna-pred.com/Hybrid_AMPPred.htm
- [x] ACEP
 https://github.com/Fuhaoyi/ACEP
- [ ] AMP-app
  https://github.com/Hayfabm/AMP-app
- [x] AI4AMP
  https://github.com/LinTzuTang/PC6-protein-encoding-method
  https://github.com/LinTzuTang/AI4AMP_predictor

The predicted AMP Probabilities of the different tools should be combined in an output like this

|Contig|Sequence|`Ampir`|`Amplify`|`EnsembleAMPPred`|`ACEP`|`AMP-app`|`AI4AMP`|
---- | ------ | ------ | ----- | ----- | ------- | ----- | ----

[transferred from old repository]

**Comment by jfy133** [comment]
Currently being evaluated by @Darcy220606

**Comment by Darcy220606** [comment]
Update : 
### Description of feature

New modules for AMP detection included in funcscan 
- [x] Amplify
  https://anaconda.org/bioconda/amplify
= Already on conda so easy to incoporate here 

- [x] EnsembleAMPPred
  http://ncrna-pred.com/Hybrid_AMPPred.htm
= Functional conda env created locally so a conda recipe can be made and included in nf-core as a module

- [x] ACEP
 https://github.com/Fuhaoyi/ACEP
= Functional conda env created locally so a conda recipe can be made and included in nf-core as a module
