### ISSUE TITLE
Clean up fARGene output

### ISSUE THREAD

**Issue by jasmezz** [nf-core/funcscan#101]
Make it optional to output temporary files in the fARGene results: `tmpdir` in each arg class subfolder might not be useful to the user. Default: no `tmpdir`.
![image](https://user-images.githubusercontent.com/73216762/181715017-1e83e0c2-0e77-4e58-9e2a-316690cb6e50.png)

**Comment by jfy133** [comment]
We should also check the HTML and see whehter we prefer the CSV output as default
