### ISSUE TITLE
Clean output directories per sample

### ISSUE THREAD

**Issue by jasmezz** [nf-core/funcscan#103]
### Description of feature

We need to clean up some output directories where multiple files per sample need to be put in individual sample folders.
For example this: 
![image](https://user-images.githubusercontent.com/73216762/181719589-a86608bc-f9de-4914-b578-1063636df948.png)
is supposed to look like this:
![image](https://user-images.githubusercontent.com/73216762/181720324-fc7def07-0f0b-4a9b-8c03-309610efeee1.png)

This is currently necessary for:
- ampir
- gecco
- hamronization
- prodigal
- rgi
- prodigal

**Comment by jfy133** [comment]
Devils advocate: this isn't necessary, as we should standardise/summarise everything with hAMRronization/AMPcombi etc., so maybe it's better to leave the output as expected for the tool (so a user can follow output docs of the given tool)

**Comment by jasmezz** [comment]
I understand, not completely convinced though. With fARGene we are already doing it (it's just adding ${meta.id} to the modules.config. Because fARGene output would look completely messy without the subfolders. So either remove its ${meta.id} or add it to all tools?

**Comment by jasmezz** [comment]
Closed by #107.
