### ISSUE TITLE
Consider using hARMonization for formatting of AMR output

### ISSUE THREAD

**Issue by jfy133** [nf-core/funcscan#12]
### Description of feature

See https://github.com/pha4ge/hAMRonization

Originally suggested by @rpetit3, who is adding the module already

**Comment by jfy133** [comment]
I would need input from @jasmezz @Darcy220606 if this would be interest/compatible with what you guys want

**Comment by Darcy220606** [comment]
I don't see why not. Its a module that combines a number of tools that screens for AMR so would be great to have it for this workflow. We are already doing something similar for the AMP workflow so that will make the code I think more consistent.

**Comment by jfy133** [comment]
Maybe you could play around based on what you've already generated in the PBT workflows and see if it contains all the info you need?

**Comment by Darcy220606** [comment]
Sounds good, ill try it out and have a look.

**Comment by rpetit3** [comment]
Also starting a list of "not on Bioconda"

AMR++ - https://github.com/meglab-metagenomics/amrplusplus_v2
c-SSTAR - https://github.com/chrisgulvik/c-SSTAR

**Comment by jfy133** [comment]
I'll work on making the harmonisation module

**Comment by jfy133** [comment]
Reopening until we have all the modules in :)

**Comment by jasmezz** [comment]
Issue for adding fARGene to the palette of supported hAMRronization summary tools: https://github.com/pha4ge/hAMRonization/issues/75

**Comment by jfy133** [comment]
OK can't do fARGene, but will now close for now and we make separate issues for each tool
