### ISSUE TITLE
Hmmsearch for amps output to sample subdirectories

### ISSUE THREAD

**Issue by Darcy220606** [nf-core/funcscan#145]
### Description of feature

AT the moment the hmmsearch writes txt files to one directory in teh AMP workflow. This needs to be changed to samplesubdir/*txt. SO that we have a standradised AMP tools output

**Comment by jfy133** [comment]
Fixed in: https://github.com/nf-core/funcscan/commit/40f5288fdaca156ff10b9d79f7ce4028fdd439e2
