### ISSUE TITLE
Last minute issues prior to pipeline release

### ISSUE THREAD

**Issue by Darcy220606** [nf-core/funcscan#196]
## Standing Issues:

# Documentation: 

- [x]  AMPCOMBI: Add column description in documentation @Darcy220606 

- [x] HAMRONIZATION: Add column description in documentation @louperelo 

- [x] COMBGC: Add column description in documentation @jasmezz 

# Full test errors:

- [x] BAKTA: FULL TEST ERROR @jasmezz 

- [x] RGI: FULL TEST ERROR @jfy133 @louperelo 

- [x]  PROKKA: FULL TEST ERROR @Darcy220606 
                        Add `--centre X` and `--compliant` flags to solve non-compliant contig name error

**Comment by jfy133** [comment]
RGI Seems to be a out of memory error that wasn't handled nicely by my cluster, I think it's running now

**Comment by jfy133** [comment]
As we've ticked everythign off :)
