### ISSUE TITLE
`BAKTA` publish dir. : divide sample files into their separate sample dir. 

### ISSUE THREAD

**Issue by Darcy220606** [nf-core/funcscan#215]
### Description of feature

Output `BAKTA` dir upon using `--save_annotations`: 
NOW: `./annotations//bakta/ *.txt/.tsv/.gbk`
SHOULD BE: `./annotations/bakta/sample1/*.txt/*tsv/*gbk`

**Comment by jfy133** [comment]
Addressed in #217
