### ISSUE TITLE
Download links for DeepARG databases are not working

### ISSUE THREAD

**Issue by jenmuell** [nf-core/funcscan#225]
### Description of the bug

I am trying to follow the usage doc to run the installation of all required database and could not manually download the databases for [DeepARG](https://nf-co.re/funcscan/1.0.0/usage#deeparg) with the provided links:

- [DeepARG FTP site](https://bench.cs.vt.edu/ftp/data/gustavo1/deeparg/database/)

- [ARGMiner service](https://bench.cs.vt.edu/argminer/#/home)

Both of dem lead in Mozilla (Version 109.0.1 (64-Bit)) and Chrome (Version 109.0.5414.121 (Offizieller Build) (64-Bit)) to connection errors.

**Comment by jfy133** [comment]
Unfortunately the server is still not up, thus the `try` in the warning message on the docs:

![image](https://user-images.githubusercontent.com/17950287/219310701-134dfef0-9a57-4b4d-9367-3325ff89482e.png)

Nothing we can do about this at the moment :(
