### ISSUE TITLE
Overly long string size in input samplesheet causes samplesheet check to erroenously report missing header

### ISSUE THREAD

**Issue by microbemarsh** [nf-core/funcscan#226]
### Description of the bug

When trying to run funcscan with more than 2 samples causes the pipeline to fail. [slack channel thread](https://app.slack.com/client/TE6CZUZPH/C02K5GX2W93/thread/C02K5GX2W93-1676906553.267839)

### Command used and terminal output

```console
nextflow run nf-core/funcscan --input funcscan_SLR25hyb.csv --outdir SLR25_hyb -profile docker --run_amp_screening --run_arg_screening --run_bgc_screening --amp_skip_amplify --arg_skip_deeparg --amp_skip_hmmsearch --bgc_skip_hmmsearch -r 1.0.0

######################################################################################

 Error executing process > 'NFCORE_FUNCSCAN:FUNCSCAN:INPUT_CHECK:SAMPLESHEET_CHECK (funcscan_SLR25hyb.csv)'

Caused by:
  Process `NFCORE_FUNCSCAN:FUNCSCAN:INPUT_CHECK:SAMPLESHEET_CHECK (funcscan_SLR25hyb.csv)` terminated with an error exit status (1)

Command executed:

  check_samplesheet.py \
      funcscan_SLR25hyb.csv \
      samplesheet.valid.csv
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_FUNCSCAN:FUNCSCAN:INPUT_CHECK:SAMPLESHEET_CHECK":
      python: $(python --version | sed 's/Python //g')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
  [CRITICAL] The given sample sheet does not appear to contain a header.
```

### Relevant files

[Link to 6 mags and csv file](https://drive.google.com/drive/folders/1AFpmkaY0qw1TK_wsAoQvQ1sTbl4QsgQP?usp=share_link)

### System information

Nextflow version 22.10.6.5843
Local Server
Local
Docker
Ubuntu Linux
nf-core/funcscan -r 1.0.0

**Comment by jfy133** [comment]
After a bit of experimenting (see end of the slack message above) it seems that if we reduce the number of new lines to check in the [samplesheet_check.py](https://github.com/nf-core/tools/blob/99961bedab1518f592668727a4d692c4ddf3c336/nf_core/pipeline-template/bin/check_samplesheet.py#L133-L140) down to 2 in the `read_head()` function, it then works.

@Midnighter believes he may have actually found a bug in python itself (:scream: ), and possibly suggests it might be easier to just use pandas for all of this...
