### ISSUE TITLE
deeparg bioconda singularity container is borked

### ISSUE THREAD

**Issue by jfy133** [nf-core/funcscan#23]
### Description of the bug

Need to to fix it (this module will plague me forever it seems...)

I'm hoping warning and error is related. I'll try and add g++ to the conda recipe under `run` 

```
❯ cat .command.log
/usr/local/lib/python2.7/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
Traceback (most recent call last):
  File "/usr/local/bin/deeparg", line 7, in <module>
    from deeparg.entry import main
  File "/usr/local/lib/python2.7/site-packages/deeparg/entry.py", line 10, in <module>
    import deeparg.predict.bin.deepARG as clf
  File "/usr/local/lib/python2.7/site-packages/deeparg/predict/bin/deepARG.py", line 12, in <module>
    from lasagne import layers
  File "/usr/local/lib/python2.7/site-packages/lasagne/__init__.py", line 27, in <module>
    import pkg_resources
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws = cls()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 567, in __init__
    self.add_entry(entry)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 623, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2065, in find_on_path
    for dist in factory(fullpath):
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2135, in distributions_from_metadata
    root, entry, metadata, precedence=DEVELOP_DIST,
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2592, in from_location
    py_version=py_version, platform=platform, **kw
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2994, in _reload_version
    md_version = self._get_version()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2772, in _get_version
    version = _version_from_file(lines)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2556, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2767, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1432, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1420, in get_metadata
    value = self._get(path)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1616, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/Theano-0.8.2-py2.7.egg-info/PKG-INFO'
```

**Comment by jfy133** [comment]
Note to self

```
conda build
```

then to load that environment 

```
conda create -n deeparg --use-local deeparg
```

apparently to build a docker container from the conda env...

```
conda index /home/jfellows/.conda/conda-bld/deeparg_1646292* ## modified from biocontainers docs but produce some console log for half a sceond?
mulled-build build-and-test 'deeparg' --test 'deeparg -h' -c conda-forge,bioconda,file://home/jfellows/.conda/conda-bld/
```

specifying the specific verison of deeparg didn't seem to work though

**Comment by jfy133** [comment]
@Midnighter identified that the ErrNo files are not allowed to be read at all, even when in the docker container?!

```
bash-4.2# cd /usr/local/lib/python2.7/site-packages/Theano-0.8.2-py2.7.egg-info/ 
bash-4.2# ls -l
total 48
-rw-r-----    1 root     root         11440 Aug  4  2016 PKG-INFO
-rw-r-----    1 root     root         19460 Aug  4  2016 SOURCES.txt
-rw-r-----    1 root     root             1 Aug  4  2016 dependency_links.txt
-rw-r-----    1 root     root            47 Apr 21  2016 pbr.json
-rw-r-----    1 root     root           112 Aug  4  2016 requires.txt
-rw-r-----    1 root     root             7 Aug  4  2016 top_level.txt
```

**Comment by jfy133** [comment]
Suggestion again from @Midnighter :

update the DerpARG bioconda recipe to patch the files.

So move the `pip install` command under `build`, make a dedicated `build.sh` file, where that command is ran and immediately after change the permissions

**Comment by jfy133** [comment]
Maybe `chmod +r /usr/local/lib/python2.7/site-packages/Theano-0.8.2-py2.7.egg-info`

**Comment by jfy133** [comment]
First attmpet:

```
#!/bin/bash
set -eu -o pipefail

python -m pip install --no-deps .

find "$PREFIX" -name '*egg-info'
chmod -R +r "$PREFIX/usr/local/lib/python2.7/site-packages/Theano-0.8.2-py2.7.egg-info"
ls -lha "$PREFIX/usr/local/lib/python2.7/site-packages/Theano-0.8.2-py2.7.egg-info/"*
```

**Comment by jfy133** [comment]
We suspect the specific version of the recipe of theano used was SO OLD it had broken permissions that with modern tooling don't work (making it too restrictive). So the above should loosen those permissions (we hope)

**Comment by jfy133** [comment]
That didn't work either, so going to remove support for DeepaRG for now

**Comment by Midnighter** [comment]
I was thinking, what if we change the `docker.runOptions` or singularity one (whichever failed) to run this single process as root?

**Comment by Midnighter** [comment]
Currently, I don't have singularity installed but might get around to it.

**Comment by jfy133** [comment]
Ah ok, I'll see if I can find the relevent options

**Comment by jfy133** [comment]
https://sylabs.io/guides/3.5/user-guide/fakeroot.html

**Comment by jfy133** [comment]
This does actually work, but not sure how to customise `runOptions` on  a per-process basis

**Comment by jfy133** [comment]
Lets see if this is possible...

**Comment by jfy133** [comment]
It is! `--fakeroot`! And on a per-process basis with `containerOptions`! Thanks and :cookie:  to @bentsherman!

**Comment by jfy133** [comment]
Ah, hit a limitation though:

![image](https://user-images.githubusercontent.com/17950287/158532076-b68ebee6-4d31-4978-953f-0d58f7cc991e.png)

**Comment by jfy133** [comment]
We need AWS batch support for the full_tests :\

**Comment by jfy133** [comment]
Ah but it's only singularity is effected, so if we can turn on container options only for singularity runs then that would work :thinking:

**Comment by Midnighter** [comment]
Should be possible with

```nextflow
containerOptions "${workflow.containerEngine == 'singularity' ? '--fakeroot' : ''}"
```

**Comment by jfy133** [comment]
Aha, `workflow.` is the trick (are all these variables listed anywhere on hte nf docs?)

**Comment by Midnighter** [comment]
For workflow you can find it here https://www.nextflow.io/docs/latest/metadata.html, I haven't found a list yet for `task` introspection.

**Comment by bentsherman** [comment]
Support for AWS Batch was only added recently, check the [edge docs](https://www.nextflow.io/docs/edge/aws.html#container-options).

Currently `containerOptions` is not supported by Kubernetes, Google Life Sciences, or Azure.

**Comment by jfy133** [comment]
The workaround is in.

@pontus has also kindly pointed a possibly more safe and more portable solution which is to make our own copy of PKG-INFO, and pass that with bind paths

```
singularity run -B PKG-INFO:/usr/local/lib/python2.7/site-packages/Theano-0.8.2-py2.7.egg-info/PKG-INFO
```

This is a nice solution as `-B` is pretty ubiquitous across most versions of singularity AFAIK, however we would need a way to store this file alongside the module and gets staged.

Or we just make that a required input file....?

**Comment by jfy133** [comment]
@Midnighter thinks it's required... but I can just dump it onto test-datasets ;)

**Comment by Midnighter** [comment]
If `pkg_resources.get_distribution` is happy with parsing an empty file, then an empty file also works. I doubt the actual version string is used anywhere (but I don't know for certain).

**Comment by jfy133** [comment]
Ok `touch PKG-INFO` doesn't work because (obviously) container is loaded before script block is executed.

But I will try just executing against `multiqc_config.yaml` so we don't need to have have a specific file

**Comment by jfy133** [comment]
I think we fixed in the end :+1:

**Comment by hugolefeuvre** [comment]
I'm currently wrapping the deepARG tool so that it can be integrated into Galaxy, which requires the tool to be tested. These tests are carried out automatically in a Docker container with a Docker pull of the biocontainer of interest (in this case deepARG). 
**And I'm encountering the exact same error as the one in this issue.** 
So I was wondering if you can remember how you solved this problem and if you could explain it more precisely because I don't understand how it was solved with the existing comments. 
Thanks in advance if anyone comes across it.

**Comment by jfy133** [comment]
Hi @hugolefeuvre !

Basically we ended up just mounting a dummy file (the bash binary of the execution node) to with the name of PKG_INFO to satisfy it: 

https://github.com/nf-core/funcscan/blob/master/modules%2Fnf-core%2Fdeeparg%2Fpredict%2Fmain.nf#L10-L18

Not ideal but we've not had any one report issues with it yet

**Comment by hugolefeuvre** [comment]
It worked perfectly, thanks @jfy133 !
