### ISSUE TITLE
Unify output of workflow summary tools

### ISSUE THREAD

**Issue by jasmezz** [nf-core/funcscan#233]
### Description of feature

It would be nice to have a congruent way of the three summary tools (AMPcombi, hAMRonization, comBGC) to output their result tables. This means mainly common column headers (e.g. `sample` vs. `sample_name` vs. `Sample_ID`) should be unified. We should also check for other things (e.g. 0- or 1-based countig for gene positions and lengths...).

**Comment by Darcy220606** [comment]
So for AMPcombi v.0.1.9 its not set as:
- For samples: the column containing sample id should be named: 'sample_name'
- For contigs: the column containing contig id should be named: 'contig_name'

**Comment by Darcy220606** [comment]
Done for ampcombi, combgc - not yet done for hamronization
