### ISSUE TITLE
Consider creating another module for macrel (peptides)

### ISSUE THREAD

**Issue by Darcy220606** [nf-core/funcscan#24]
### Description of feature

As the 6 other amp detection tools require prokka annotated files as input, it would be better if the macrel module also accepts prokka output as input. The current macrel/contig module only runs na sequences.

**Comment by jfy133** [comment]
After discussion with Louisa and also the developer of Macrel on #42 , we decided it is not necessary as Macrel has a modified version of prodigal that allows analysis of shorter genes
