### ISSUE TITLE
AMPcombi does not execute when only MACREL

### ISSUE THREAD

**Issue by jfy133** [nf-core/funcscan#241]
### Description of the bug

We currently use the macrel subcommand that does it's own annotations, therefore we do not run annotation in the pipeline when specifying macrel only. In this case a `join` of the FAA back to the FNA doesn't occur meaning AMPcombi does not recieve input.

We should switch from `macrel contigs` to `macrel peptides`

**Comment by jasmezz** [comment]
Solved by #242
