### ISSUE TITLE
Add QC check after annotation to avoid empty annotation files being screened

### ISSUE THREAD

**Issue by alexhbnr** [nf-core/funcscan#246]
### Description of feature

When poor quality data are used as input into nf-core/funcscan, the initial annotation step might not return a single annotation but produce an empty FastA file. Currently, the workflow attempts to profile this empty FastA file in the subsequent workflows, leading to a failure of a task. After the whole pipeline has finished, there is an overview of the execution of the pipeline and it will list the number of failed tasks. However, from this report it is not apparent that it failed because there were no input data available from the start.

It would be great, if either
a) there is a test after the annotation step that discards such samples and doesn't attempt to profile them
or
b) provides a more informative error message that indicates that the tasks failed due to insufficient input data.

**Comment by jfy133** [comment]
@alexhbnr do you have an example of an empty FASTA file? Or is it literally just equivalent to `touch <filename>.fasta`?

**Comment by alexhbnr** [comment]
The latter. It's completely empty.

**Comment by jfy133** [comment]
Maybe we can check file size with: https://www.nextflow.io/docs/latest/script.html#check-file-attributes
