### ISSUE TITLE
replace System.exit

### ISSUE THREAD

**Issue by louperelo** [nf-core/funcscan#257]
### Description of the bug

Learned today that we should avoid using `System.exit` and replace it with `Nextflow.error` like done in this [Sarek PR](https://github.com/nf-core/sarek/pull/982/files)

### Relevant files

.nf-core-yml
NfcoreSchema.groovy
WorkflowFuncscan.groovy
WorkflowMain.groovy

**Comment by jfy133** [comment]
We've done this for all funcscan code: https://github.com/nf-core/funcscan/pull/248/files

All other instances will come in the next tools release
