### ISSUE TITLE
Parameters Site Unavailable

### ISSUE THREAD

**Issue by akp1d12** [nf-core/funcscan#260]
### Description of the bug

Bug report: Trying to access the parameter document results in a 503 Service Unavailable error.
I have replicated this on two different devices using wifi and mobile data.
Is there another site where paramter info may be available?
Thank you for the wonderful tool
Anish

**Comment by jfy133** [comment]
Hi @akp1d12 this should be fixed now - I can access myself for example :)

https://github.com/nf-core/funcscan

**Comment by akp1d12** [comment]
Thank you so much, i was making notes on the .yaml yesterday too.
Much appreciated

Anish
