### ISSUE TITLE
Check DRAMP db download folder

### ISSUE THREAD

**Issue by louperelo** [nf-core/funcscan#271]
### Description of feature

The DRAMP database is downloaded into a folder, which is outside the `database` folder. Would be nicer to have all downloaded databases in there. Is this, because DRAMP is downloaded always, but other databases only if the flag is activated?

**Comment by jasmezz** [comment]
Yep, that is a good point! Looks like no-one really cared about it yet: There is no entry in modules.config. So let's handle it in the same way as the other databases – store it in the `database` folder if the AMP workflow is run and if user wants the database(s).
