### ISSUE TITLE
Apply nf-test on funcscan

### ISSUE THREAD

**Issue by louperelo** [nf-core/funcscan#280]
### Description of feature

See description on nf-test [here](https://hackmd.io/@Fe-DlBDORpeApqPrKRTlbA/SJVrM7uHh#/)
See bitesize talk on nf-test implementation [here](https://www.youtube.com/watch?v=MuwluoKFnwM)

Modules in this pipeline which will need to have nf-test implemented:
- [x] abricate/run
- [x] ampcombi
- [x] ampir
- [x] amplify/predict
- [ ] amrfinderplus
- [ ] antismash
- [x] bakta
- [ ] bioawk
- [x] custom/dumpsoftwareversions
- [ ] deeparg
- [x] deepbgc
- [x] fargene
- [ ] gecco/run
- [x] gunzip
- [ ] hamronization
- [ ] hmmer/hmmsearch
- [x] macrel/contigs
- [ ] multiqc
- [x] prodigal
- [x] prokka
- [x] pyrodigal
- [ ] rgi/main
- [ ] tabix/bgzip
- [x] untar

**Comment by jfy133** [comment]
Done in with nf-test at pipeline level [here](https://github.com/nf-core/funcscan/pull/366)

For other modules, these will happen over time
