### ISSUE TITLE
Incorrect docker container uris

### ISSUE THREAD

**Issue by sunitj** [nf-core/funcscan#281]
### Description of the bug

I seem to be getting errors like this with v1.1.1 with the `docker` profile:

```bash
nextflow.exception.ProcessUnrecoverableException: Task failed to start - CannotPullContainerError: Error response from daemon: pull access denied for nf-core/ubuntu, repository does not exist or may require 'docker login': denied: requested access to the resource is denied;
```

I tested by downloading `nf-core/ubuntu` manually, but I get the same error:

```bash
$ docker pull nf-core/ubuntu:20.04
Using default tag: latest
Error response from daemon: pull access denied for nf-core/ubuntu, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

To ensure that this wasn't an actual issue with my user. I also tried downloading the `hello-world` image, and that worked.
```bash
$ docker pull hello-world
Using default tag: latest
latest: Pulling from library/hello-world
719385e32844: Pull complete
Digest: sha256:fc6cf906cbfa013e80938cdf0bb199fbdbb86d6e3e013783e5a766f50f5dbce0
Status: Downloaded newer image for hello-world:latest
docker.io/library/hello-world:latest
```

Further investigation, seem to also indicate that URIs should start with `quay.io/biocontainers/` start with `biocontainers` instead. 

### Relevant files

Here is a summary of all the incorrect URIs I could find and what I think they should be.

| file | current docker URI | correct docker URI |
|--------|--------|--------|
| nf-core/gunzip/main.nf | 'nf-core/ubuntu:20.04' | 'ubuntu:20.04' |
| nf-core/untar/main.nf | 'nf-core/ubuntu:20.04' | 'ubuntu:20.04' |
| nf-core/ampcombi/main.nf | 'biocontainers/ampcombi:0.1.7--pyhdfd78af_0' | 'quay.io/biocontainers/ampcombi:0.1.7--pyhdfd78af_0' |
| nf-core/ampir/main.nf | 'biocontainers/r-ampir:1.1.0' | 'quay.io/biocontainers/r-ampir:1.1.0' |
| nf-core/bioawk/main.nf | 'biocontainers/bioawk:1.0--h5bf99c6_6' | 'quay.io/biocontainers/bioawk:1.0--h5bf99c6_6' |
| nf-core/fargene/main.nf | 'biocontainers/fargene:0.1--py27h21c881e_4' | 'quay.io/biocontainers/fargene:0.1--py27h21c881e_4' |
| nf-core/fastqc/main.nf | 'biocontainers/fastqc:0.11.9--0' | 'quay.io/biocontainers/fastqc:0.11.9--0' |
| nf-core/multiqc/main.nf | 'biocontainers/multiqc:1.14--pyhdfd78af_0' | 'quay.io/biocontainers/multiqc:1.14--pyhdfd78af_0' |
| nf-core/prodigal/main.nf | 'biocontainers/mulled-v2-2e442ba7b07bfa102b9cf8fac6221263cd746ab8:57f05cfa73f769d6ed6d54144cb3aa2a6a6b17e0-0' | 'quay.io/biocontainers/mulled-v2-2e442ba7b07bfa102b9cf8fac6221263cd746ab8:57f05cfa73f769d6ed6d54144cb3aa2a6a6b17e0-0' |
| nf-core/prokka/main.nf | 'biocontainers/prokka:1.14.6--pl5321hdfd78af_4' | 'quay.io/biocontainers/prokka:1.14.6--pl5321hdfd78af_4' |
| nf-core/pyrodigal/main.nf | 'biocontainers/mulled-v2-2fe9a8ce513c91df34b43a6610df94c3a2eb3bd0:697b3838b186fac6a9ceec198b09d4032162a079-0' | 'quay.io/biocontainers/mulled-v2-2fe9a8ce513c91df34b43a6610df94c3a2eb3bd0:697b3838b186fac6a9ceec198b09d4032162a079-0' |

### System information

Nextflow: 23.04.1
Hardware: EC2 instance
Executor: local and AWS Batch
Container engine: Docker
OS: Amazon Linux 2
nf-core/funcscan version: 1.1.1

**Comment by jfy133** [comment]
I think this might be related to https://github.com/nf-core/funcscan/pull/279

**Comment by jfy133** [comment]
And by related, I mean solved

**Comment by jfy133** [comment]
@sunitj could you see if running with `-r dev` solves the problem? (x-post from slack)

**Comment by sunitj** [comment]
@jfy133 I'm not sure if this is related, but I'm getting this error:

```bash
pigz: skipping: SPAdes-MetaBAT2-group-H1167_CA004_2060.45.fa is a symbolic link
```

More context:
```bash
Jun-01 17:53:54.392 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=NFCORE_FUNCSCAN:FUNCSCAN:PYRODIGAL (SPAdes-MetaBAT2-group-H1167_CA004_2060.45); work-dir=/mnt/efs/scratch/sunit/funcscan/TEST/20230601_dev/work/d1/3773d8c81bf52d679490e68c0ed00d
  error [nextflow.exception.ProcessFailedException]: Process `NFCORE_FUNCSCAN:FUNCSCAN:PYRODIGAL (SPAdes-MetaBAT2-group-H1167_CA004_2060.45)` terminated with an error exit status (1)
Jun-01 17:53:54.408 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'NFCORE_FUNCSCAN:FUNCSCAN:PYRODIGAL (SPAdes-MetaBAT2-group-H1167_CA004_2060.45)'

Caused by:
  Process `NFCORE_FUNCSCAN:FUNCSCAN:PYRODIGAL (SPAdes-MetaBAT2-group-H1167_CA004_2060.45)` terminated with an error exit status (1)

Command executed:

  pigz -cdf SPAdes-MetaBAT2-group-H1167_CA004_2060.45.fa > pigz_fasta.fna
  
  pyrodigal \
      -p meta   -g 11 \
      -i pigz_fasta.fna \
      -o SPAdes-MetaBAT2-group-H1167_CA004_2060.45.gff \
      -d SPAdes-MetaBAT2-group-H1167_CA004_2060.45.fna \
      -a SPAdes-MetaBAT2-group-H1167_CA004_2060.45.faa \
      -s SPAdes-MetaBAT2-group-H1167_CA004_2060.45.score
  
  pigz -nm SPAdes-MetaBAT2-group-H1167_CA004_2060.45*
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_FUNCSCAN:FUNCSCAN:PYRODIGAL":
      pyrodigal: $(echo $(pyrodigal --version 2>&1 | sed 's/pyrodigal v//'))
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  pigz: skipping: SPAdes-MetaBAT2-group-H1167_CA004_2060.45.fa is a symbolic link

Work dir:
  /mnt/efs/scratch/sunit/funcscan/TEST/20230601_dev/work/d1/3773d8c81bf52d679490e68c0ed00d

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
```

Running the `.command.run` separately:

```bash
$ cd /mnt/efs/scratch/sunit/funcscan/TEST/20230601_dev/work/d1/3773d8c81bf52d679490e68c0ed00d
$ bash .command.run
pigz: skipping: SPAdes-MetaBAT2-group-H1167_CA004_2060.45.fa is a symbolic link
pigz: skipping: SPAdes-MetaBAT2-group-H1167_CA004_2060.45.faa.gz exists
pigz: skipping: SPAdes-MetaBAT2-group-H1167_CA004_2060.45.faa.gz ends with .gz
pigz: skipping: SPAdes-MetaBAT2-group-H1167_CA004_2060.45.fna.gz exists
pigz: skipping: SPAdes-MetaBAT2-group-H1167_CA004_2060.45.fna.gz ends with .gz
pigz: skipping: SPAdes-MetaBAT2-group-H1167_CA004_2060.45.gff.gz exists
pigz: skipping: SPAdes-MetaBAT2-group-H1167_CA004_2060.45.gff.gz ends with .gz
pigz: skipping: SPAdes-MetaBAT2-group-H1167_CA004_2060.45.score.gz exists
pigz: skipping: SPAdes-MetaBAT2-group-H1167_CA004_2060.45.score.gz ends with .gz
```

Command used:

```bash
nextflow run nf-core/funcscan \
    -r dev \
    --input test_samplesheet.csv \
    --outdir CA004 \
    -profile docker \
    --run_bgc_screening \
    --save_databases \
    --bgc_skip_hmmsearch
```

**Comment by sunitj** [comment]
For a little more context, I was able to run the same `test_samplesheet.csv` using the same command (except the `-r dev`) without any issues on `v1.1.0`.

**Comment by jfy133** [comment]
Should be fixed in: https://github.com/nf-core/funcscan/pull/279

1.1.2 coming imminentnyl!
