### ISSUE TITLE
Include Contig taxonomic classification before going into the summary modules

### ISSUE THREAD

**Issue by Darcy220606** [nf-core/funcscan#318]
### Description of feature

This is very useful to include contig taxonomic classification, before running the summary modules. This can greatly enhance the function of the summary modules by adding the source of the BGC/AMP/ARG. This can be done with MMseqs2/minimap2/blast/diamond

**Comment by jfy133** [comment]
Wouldn't this be best served by other pipelines, e.g. taxprofiler (improved longread support coming in the next release :)))
