### ISSUE TITLE
Update hAMRonization to v1.1.4

### ISSUE THREAD

**Issue by louperelo** [nf-core/funcscan#321]
### Description of feature

hAMRonization had some new releases and is on v1.1.4 now (our modules are on 1.1.1). It now includes `contig_ids`, which are named `input_sequence_id` in the output.
Needs to update modules:
- [x] hamronization/abricate
- [x] hamronization/amrfinderplus
- [x] hamronization/deeparg
- [x] hamronization/fargene
- [x] hamronization/rgi
- [x] hamronization/summarize

**Comment by jasmezz** [comment]
Closed by [#4878](https://github.com/nf-core/modules/pull/4878)
