### ISSUE TITLE
Update Bakta to 1.9.2

### ISSUE THREAD

**Issue by jasmezz** [nf-core/funcscan#325]
### Description of feature

Update Bakta to most recent version 1.9.2. In the old version, CDS coordinates were sometimes wrong (bug see bakta changelog)!

**Comment by jasmezz** [comment]
Module update for baktadbdownload: https://github.com/nf-core/modules/pull/4822

**Comment by jfy133** [comment]
Done in https://github.com/nf-core/funcscan/pull/332
