### ISSUE TITLE
Add missing essential parameters for antismash

### ISSUE THREAD

**Issue by Darcy220606** [nf-core/funcscan#356]
### Description of feature

The new version of antismash requires essential parametrs that i would suggest to be included in the pipeline. Those are `pfam2go --rre --tfbs` at the moment i add them using ext.args in the default runs.

**Comment by jfy133** [comment]
@Darcy220606 does this still apply?

**Comment by jasmezz** [comment]
I added those params to the pipeline in the above PR.
@Darcy220606 Do you have more description than what is given by the `antismash --help`? The documentation gives nothing :upside_down_face: It would be nice to fill the params help text a bit more, but it is not a must.

**Comment by Darcy220606** [comment]
> I added those params to the pipeline in the above PR. @Darcy220606 Do you have more description than what is given by the `antismash --help`? The documentation gives nothing 🙃 It would be nice to fill the params help text a bit more, but it is not a must.

They all basically add more annotation to the BGC to allow for better selection for downstream experimental processing:
- `pfam2go`: maps the proteins to PFAM db.This helps annoate BGC modules with functional information based on the protein families they contain.
- `rre`: predicts regulatory elements on the BGC that help in teh control of expression of the peptides/proteins
- `tfbs`: predicts the transcription factor binding sites, again which helps in regulation of expression

**Comment by jasmezz** [comment]
Done in #403
