### ISSUE TITLE
deeparg 1.0.4 required to correctly fetch DBs

### ISSUE THREAD

**Issue by m3hdad** [nf-core/funcscan#370]
### Description of the bug

deeparg 1.0.2 is using an old repository path to download the databases (https://bench.cs.vt.edu/ftp/) which does not exist.

deeparg 1.0.4 fetches data correctly from https://zenodo.org/records/8280582/files/deeparg.zip.
Singularity container is available for the new version.

**Comment by jfy133** [comment]
Thanks @m3hdad ! This is already solved in the upcoming release :)

https://github.com/nf-core/funcscan/commit/8ccd1b15e6982c503ed066c5d67454ee957c19a9
