### ISSUE TITLE
In some cases RGI will not produce all files expected for mving for publishing

### ISSUE THREAD

**Issue by jfy133** [nf-core/funcscan#376]
### Description of the bug

https://nfcore.slack.com/archives/C02K5GX2W93/p1715619477736569

Just need to make ,mv. commands only executed if present

**Comment by jfy133** [comment]
Module in, juyst need to update

**Comment by amizeranschi** [comment]
Hey @jfy133

Thanks a lot for following up on this issue. I've tested the following replacement for the mv command and it got RGI working fine for me:

```
for FILE in *.xml *.fsa *.{nhr,nin,nsq} *.draft *.potentialGenes *{variant,rrna,protein,predictedGenes,overexpression,homolog}.json; do [[ -e \$FILE ]] && mv \$FILE temp/; done
```

**Comment by jfy133** [comment]
Oh nice @amizeranschi ! That's much better than my solution...

I updated the module over at nf-core/modules, so you get credit, could you make a PR replacing  my horrible copypasta over there and ping me for review? Then we can update the pipeline :)

**Comment by amizeranschi** [comment]
This should now be fixed by https://github.com/nf-core/modules/pull/5614

**Comment by jfy133** [comment]
Reopened until update is in pipeline :)
