### ISSUE TITLE
comBGC column BGC_length inaccurate

### ISSUE THREAD

**Issue by martinklapper** [nf-core/funcscan#399]
### Description of the bug

The BGC_length column often reports the BGC length with 1 nucleotide more than the actual contig length, which is not possible. The calculation of this column seems to be wrong.
[bug_BGC_length.xlsx](https://github.com/user-attachments/files/16190556/bug_BGC_length.xlsx)

**Comment by jfy133** [comment]
@jasmezz is this already fixed in the pipeline version V2?
