### ISSUE TITLE
Add the Prodigal module to the pipeline

### ISSUE THREAD

**Issue by louperelo** [nf-core/funcscan#44]
### Description of feature

Prodigal should be added to be the default tool for gene annotation, which is needed for several tools (AMP tools and DeepARG, etc.). Prokka should be the optional way, if the user wants functional annotation as well.

**Comment by Darcy220606** [comment]
Working on it in the forked branch add_prodigal here https://github.com/Darcy220606/funcscan/tree/add_prodigal

**Comment by jfy133** [comment]
Donie in: https://github.com/nf-core/funcscan/pull/59
