### ISSUE TITLE
Consider adding annotated contigs as main input to the pipeline

### ISSUE THREAD

**Issue by Darcy220606** [nf-core/funcscan#47]
### Description of feature

After talking to Martin Klapper today, he suggests that we add annoted contigs as a main input to the pipeline (besided assembly contigs) and and mke it an option to switch off the entire annotation step (prodigal and prokka), especially if we also cite that the output from MAG pipeline can be used as an input to funcscan.

**Comment by jfy133** [comment]
We've hit a problem with optionally including annotated contigs as input.

I've actually got this working, however the code has got quite messy now. But this has also led to two issues which makes me feel like I would rather _not_ support this:

1. DeepARG takes as input specifically nucleotide fasta out of PROKKA. Therefore if we don't run PROKKA on those samples that are supplied _with_ the annotation fasta file, then those samples will not be executed by PROKKA. I.e. we would always have to run PROKKA on everything anyway regardless
2.  After thinking about it, I am also now concerned about version and software consistency. By allowing users supply their own FAA files, this could be from versions different from what we have in the pipeline, and in fact could be from different tools that may not be supported by other steps of our pipeline.

Therefore I would actually rather _not_ support this. If you're concerned about speed, you could just Prodigal instead.

What do you think about this?

**Comment by jfy133** [comment]
I got an OK to skip this from Martin, and with the addition of Prodigal this should massively speed up the process anyway of those who are concerned about run time.
