### ISSUE TITLE
AMP Summary Table

### ISSUE THREAD

**Issue by jfy133** [nf-core/funcscan#63]
### Description of feature

Should produce two files:

-  summary (Sample_Name,Tool,No_Hits)
- aggregated (Sample_Name,Tool,Contig,Hit_Name,Probability,....)

**Comment by jfy133** [comment]
With ampCOMBI

**Comment by Darcy220606** [comment]
New issue to add the AMPcombi module ::: https://github.com/nf-core/modules/issues/2183
