### ISSUE TITLE
deepARG database currently inaccessible

### ISSUE THREAD

**Issue by louperelo** [nf-core/funcscan#70]
### Description of the bug

As the deepARG databases are currently inaccessible, `--arg_skip_deeparg` was set to `true` temporarily in the funcscan `test.config` to avoid the failing of the test runs. As soon as the problem is resolved by the maintainers of deepARG, the tool should be included in the test runs again.

**Comment by jfy133** [comment]
I have emailed the lab head of the DeepARG Developers on 2022-06-29

**Comment by jfy133** [comment]
It's back, server was under maintainence, I've reactivated the running of deepARG
