### ISSUE TITLE
Ensure all tools have relevant critical parameters accessible at pipeline level

### ISSUE THREAD

**Issue by jfy133** [nf-core/funcscan#80]
We need  to make sure that all (relevant) parameters that a user may want to tweak of a given tool are available to be modifiable by the pipelie user (see deepARG, where this is already added).

Before release we should do a pass to check every tool and insert params where necessary.

**Comment by Darcy220606** [comment]
Check parametrs in all modules in the workflows:
## AMP workflow
- [  ]  Macrel
- [  ]  Amplify
- [  ]  ampir
- [  ]  hmmsearch
## BGC workflow
- [  ]  antismash
- [  ]  gecco
- [  ]  deepbgc
## ARG workflow
- [  ]  AMRFINDERPLUS
- [  ]  Fargene
- [  ]  RGI
- [  ]  abricate
- [  ]  deeparg
## Annotations
- [  ]  Prodigal
- [  ]  Prokka
- [  ]  Bakta
## Reports
- [  ]  ampcombi
- [  ]  hamronisation
- [  ]  combgc
